name: Release

on:
  push:
    branches:
      - main


env:
  IMAGE_OWNER: "foexle"
  IMAGE_TITLE: "deploykf_dashboard"
  IMAGE_DESCRIPTION: "Dashboard for deployKF"
  IMAGE_FOLDER: "dashboard"
  IMAGE_PLATFORMS: |-
    linux/amd64
    linux/arm64
 

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install QEMU
        uses: docker/setup-qemu-action@v2
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.IMAGE_FOLDER }}
          push: true
          platforms: ${{ env.IMAGE_PLATFORMS }}
          tags: latest
          labels: latest
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_OWNER }}/ci/${{ env.IMAGE_TITLE }}
          cache-to: type=registry,ref=ghcr.io/${{ env.IMAGE_OWNER }}/ci/${{ env.IMAGE_TITLE }},mode=max