name: Release

on:
  push:
    branches:
      - main


env:
  IMAGE_OWNER: "foexle"
  IMAGE_TITLE: "deploykf_dashboard"
  IMAGE_DESCRIPTION: "Dashboard for deployKF"
  IMAGE_FOLDER: "dashboard"
  IMAGE_PLATFORMS: |-
    linux/amd64

 

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.IMAGE_FOLDER }}
          push: true
          file: ./Dockerfile
          builder: default
          platforms: ${{ env.IMAGE_PLATFORMS }}
          tags: latest
          labels: latest
